version: '2'

services:
    nextcloud:
        image: nextcloud:18.0-fpm-alpine
        env_file:
            - .env
        volumes:
            - nextcloud:/var/www/html
        restart: unless-stopped

    nginx:
        image: nginx
        ports:
            - 8080:80
        links:
            - nextcloud
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
            - nextcloud
        restart: unless-stopped

volumes:
    nextcloud:
