version: '3.7'

services:
    nextcloud:
        image: nextcloud:${NEXTCLOUD_TAG:-18.0-fpm-alpine}
        env_file:
            - .env
        volumes:
            - nextcloud:/var/www/html
            - ./nextcloud/config/objectstore.config.php:/usr/src/nextcloud/config/objectstore.config.php:ro
            - ./nextcloud/config/logs.config.php:/usr/src/nextcloud/config/logs.config.php:ro
        restart: unless-stopped

    nginx:
        image: nginx
        env_file:
            - .env
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - nextcloud:/var/www/html:ro
        restart: unless-stopped

volumes:
    nextcloud:

networks:
    default:
        external:
            name: ${NETWORK}