version: '3.5'

services:
    nginx:
        image: nginx:1.17
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - nextcloud:/var/www/html:ro
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - ${NEXTCLOUD_PORT}:80

    nextcloud:
        build:
            context: .
            dockerfile: nextcloud/Dockerfile
            args:
                ENV: "${NEXTCLOUD_VERSION}"
        #image: nextcloud:${NEXTCLOUD_VERSION}-fpm-alpine
        restart: unless-stopped
        depends_on:
          - mysql
        env_file:
            - .env
        environment:
            MYSQL_HOST: "mysql"
        volumes:
            - nextcloud:/var/www/html

    mysql:
        env_file:
            - .env
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
    nextcloud:

networks:
    default:
        external:
            name: ${NETWORK}
