version: '3.5'

services:
    nginx:
        image: nginx:1.17
        links:
            - nextcloud
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - ${NEXTCLOUD_PORT}:80

    nextcloud:
        image: nextcloud:${NEXTCLOUD_VERSION}-fpm-alpine
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./nextcloud/config.php:/var/www/html/config/config.php

    mysql:
        env_file:
            - .env
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
    nextcloud:

networks:
    default:
        external:
            name: ${NETWORK}
