version: '3.5'

services:
    nginx:
        image: nginx:1.17
        links:
            - nextcloud
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
        env_file:
            - .env
        restart: unless-stopped

    nextcloud:
        image: nextcloud:17.0-fpm-alpine
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - nextcloud:/var/www/html
            - ../nextcloud/config:/var/www/html/config
        ports:
            - ${PORT}:80

    mysql:
        env_file:
            - .env
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
    nextcloud:

networks:
    default:
        external:
            name: ${NETWORK}
